version: "3.9"

services:
  birthdaybot:
    build: .
    container_name: birthdaybot
    command: python bot/main.py
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    restart: always